parameters:
#    biberltd_currency.example.class: BiberLtd\Bundles\CurrencyBundle\Example

services:
    biberltd_currency.currency_converter:
        class:        BiberLtd\Bundles\CurrencyBundle\Services\CurrencyConverter
        arguments:
